In [1]:
import numpy as np

In [2]:
my_list  = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1, 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(1, 12, 2)

array([ 1,  3,  5,  7,  9, 11])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(6)

array([0.4965225 , 0.68300677, 0.18173711, 0.67412033, 0.44538844,
       0.62900913])

In [21]:
np.random.rand(5,5)

array([[0.29718082, 0.39999479, 0.72419216, 0.41154283, 0.6182917 ],
       [0.82712592, 0.27888067, 0.8278092 , 0.32302659, 0.28307093],
       [0.35390217, 0.50965023, 0.31223323, 0.16565633, 0.32490523],
       [0.21308037, 0.7540033 , 0.19571218, 0.74934715, 0.13259483],
       [0.77578549, 0.11009552, 0.26861167, 0.0820836 , 0.23522023]])

In [22]:
np.random.randn(2)

array([-0.34823473, -0.56666178])

In [23]:
np.random.randn(2,3)

array([[-0.52106865, -0.03615148, -0.2034248 ],
       [-0.7641883 ,  0.57539976,  0.76895446]])

In [25]:
np.random.randint(1,100, 20
                 )

array([80, 92, 84, 18, 62, 82, 83, 27, 88, 89, 87, 68, 27, 28, 76, 57, 17,
       75,  7, 10])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranArr = np.random.randint(0,200, 12)

In [35]:
ranArr

array([ 50,  12, 193,  99,  14, 180, 101,  12, 145,  22,  35, 134])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranArr.reshape(4,3)

array([[ 50,  12, 193],
       [ 99,  14, 180],
       [101,  12, 145],
       [ 22,  35, 134]])

In [39]:
ranArr.reshape(3,4)

array([[ 50,  12, 193,  99],
       [ 14, 180, 101,  12],
       [145,  22,  35, 134]])

In [40]:
ranArr.max()

193

In [41]:
ranArr.min()

12

In [43]:
ranArr.argmax()

2

In [45]:
ranArr.argmin()

1

In [47]:
ranArr.shape

(12,)

# Numpy index & selection

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr[3:16]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
arr[: 6]

array([0, 1, 2, 3, 4, 5])

In [52]:
arr_1 = np.arange(12)

In [53]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
slice_arr = arr_1[0:6]


In [57]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_arr[:] = 25

In [59]:
slice_arr

array([25, 25, 25, 25, 25, 25])

In [60]:
arr_1

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10, 11])

# COPY NEW 

In [61]:
slice_arr_1 = arr_1.copy()

In [62]:
slice_arr_1

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10, 11])

In [63]:
slice_arr_1[:] = 100

In [64]:
slice_arr_1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr_1

array([25, 25, 25, 25, 25, 25,  6,  7,  8,  9, 10, 11])

# Dimensoin Array

In [70]:
fivearr = np.arange(5,50, 5)

In [71]:
fivearr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [73]:
arr_2d  = fivearr.reshape(3,3)

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d [1][1]

25

In [78]:
arr_2d[1,1]

25

In [80]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [81]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [98]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [97]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

# conditional selection

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [102]:
bool_arr = arr > 12

In [103]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [104]:
new_arr = arr[bool_arr]

In [105]:
new_arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
new_arr2 = arr[arr % 2 == 0]

In [112]:
new_arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [119]:
check_arr = np.arange(50).reshape(5,10)

In [120]:
check_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#  grab [26, 27] [36,37]

In [122]:
check_arr[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [124]:
check_arr[2:4,6:8]

array([[26, 27],
       [36, 37]])

# Arithemic

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [127]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [128]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [131]:
arr - 24

array([-24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])